create user Harry identified by CoffeeStaff#123;        --Harry is the user who takes up the role of StoreManager or store Admin
grant connect, resource to Harry;
grant drop any table, drop any view to Harry;
grant create view to Harry;
grant create session, create table, create procedure to Harry;
ALTER USER HARRY QUOTA UNLIMITED ON DATA;
--drop user Harry cascade;
Commit;

BEGIN
EXECUTE IMMEDIATE 'CREATE role STORE_MANAGER';
EXECUTE IMMEDIATE 'CREATE role CASHIER';
EXECUTE IMMEDIATE 'CREATE role BARISTA';
EXECUTE IMMEDIATE 'CREATE role INVENTORY_MANAGER';
EXECUTE IMMEDIATE 'CREATE role ORDER_DELIVERY_EMP';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO STORE_MANAGER';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO CASHIER';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO BARISTA';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO INVENTORY_MANAGER';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ORDER_DELIVERY_EMP';

EXCEPTION
WHEN OTHERS THEN
   NULL;
END;


--DROP USER HARRY CASCADE;